# Site settings
title: Lisa &amp; Bill
email: billdami@gmail.com
description: Lisa Schmidt and Bill Dami's Wedding website - September 17th 2016
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lisaandbill.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
